// Mocks generated by Mockito 5.2.0 from annotations
// in pets_app/test/ui/pages/login/controller/login_controller_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:pets_app/domain/entities/entities.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Pet].
///
/// See the documentation for Mockito's code generation for more information.
class MockPet extends _i1.Mock implements _i2.Pet {
  @override
  List<_i2.Breed> get breeds => (super.noSuchMethod(Invocation.getter(#breeds),
      returnValue: <_i2.Breed>[]) as List<_i2.Breed>);
  @override
  set breeds(List<_i2.Breed>? _breeds) =>
      super.noSuchMethod(Invocation.setter(#breeds, _breeds),
          returnValueForMissingStub: null);
  @override
  List<_i2.Category> get categories =>
      (super.noSuchMethod(Invocation.getter(#categories),
          returnValue: <_i2.Category>[]) as List<_i2.Category>);
  @override
  set categories(List<_i2.Category>? _categories) =>
      super.noSuchMethod(Invocation.setter(#categories, _categories),
          returnValueForMissingStub: null);
  @override
  set id(String? _id) => super.noSuchMethod(Invocation.setter(#id, _id),
      returnValueForMissingStub: null);
  @override
  set url(String? _url) => super.noSuchMethod(Invocation.setter(#url, _url),
      returnValueForMissingStub: null);
  @override
  set width(int? _width) =>
      super.noSuchMethod(Invocation.setter(#width, _width),
          returnValueForMissingStub: null);
  @override
  set height(int? _height) =>
      super.noSuchMethod(Invocation.setter(#height, _height),
          returnValueForMissingStub: null);
  @override
  _i2.PetType get petType => (super.noSuchMethod(Invocation.getter(#petType),
      returnValue: _i2.PetType.dog) as _i2.PetType);
  @override
  set petType(_i2.PetType? _petType) =>
      super.noSuchMethod(Invocation.setter(#petType, _petType),
          returnValueForMissingStub: null);
}
