import 'dart:math';

import 'package:pets_app/domain/entities/entities.dart';

class RandomNamesPet {
  static String getRandomNamePet({required PetType petType}) {
    List<String> dogNames = [
      "Santiago",
      "Sebastián",
      "Matías",
      "Mateo",
      "Nicolás",
      "Alejandro",
      "Diego",
      "Samuel",
      "Benjamín",
      "Daniel",
      "Joaquín",
      "Lucas",
      "Tomas",
      "Gabriel",
      "Martín",
      "David",
      "Emiliano",
      "Jerónimo",
      "Emmanuel",
      "Agustín",
      "Juan Pablo",
      "Juan José",
      "Andrés",
      "Thiago",
      "Leonardo",
      "Felipe",
      "Ángel",
      "Maximiliano",
      "Christopher",
      "Juan Diego",
      "Adrián",
      "Pablo",
      "Miguel Ángel",
      "Rodrigo",
      "Alexander",
      "Ignacio",
      "Emilio",
      "Dylan",
      "Bruno",
      "Carlos",
      "Vicente",
      "Valentino",
      "Santino",
      "Julián",
      "Juan Sebastián",
      "Aarón",
      "Lautaro",
      "Axel",
      "Fernando",
      "Ian",
      "Christian",
      "Javier",
      "Manuel",
      "Luciano",
      "Francisco",
      "Juan David",
      "Iker",
      "Facundo",
      "Rafael",
      "Alex",
      "Franco",
      "Antonio",
      "Luis",
      "Isaac",
      "Máximo",
      "Pedro",
      "Ricardo",
      "Sergio",
      "Eduardo",
      "Bautista",
      "Miguel",
      "Cristóbal",
      "Kevin",
      "Jorge",
      "Alonso",
      "Anthony",
      "Simón",
      "Juan",
      "Joshua",
      "Diego Alejandro",
      "Juan Manuel",
      "Mario",
      "Alan",
      "Josué",
      "Gael",
      "Hugo",
      "Matthew",
      "Ivan",
      "Damián",
      "Lorenzo",
      "Juan Martín",
      "Esteban",
      "Álvaro",
      "Valentín",
      "Dante",
      "Jacobo",
      "Jesús",
      "Camilo",
      "Juan Esteban",
      "Elías"
    ];

    List<String> catNames = [
      "Mr Pratik Skaggs",
      "Mr Uehudah Hack",
      "Mr Edison Drye",
      "Ms Mihoko Scholl",
      "Mr Ajani Harding",
      "Ms Ruthie Coco",
      "Mr Orazio Hart",
      "Ms Vinaya Justus",
      "Mr Tristan Karns",
      "Ms Ardath Enriquez",
      "Ms Usagi Denny",
      "Ms Sevita Hershberger",
      "Ms Carnation Dingman",
      "Mr Niven Glaser",
      "Mr Derwyn Devers",
      "Ms Rossa Fanning",
      "Mr Tod Phan",
      "Mr Eddie Hulse",
      "Mr Welford Yepez",
      "Mr Rishley Snyder",
      "Mr Milo Mccurdy",
      "Ms Sammi Zepeda",
      "Ms Romaine Dingman",
      "Ms Almeda Hack",
      "Ms Colette Hon",
      "Mr Carden Justus",
      "Mr Carlyon Gorby",
      "Mr Mungo Spangler",
      "Ms Berwyn Philip",
      "Ms Helen Messinger",
      "Mr Whitmore Squires",
      "Ms Sunita Poulos",
      "Ms Sevita Poulos",
      "Mr Pedrog Mccurdy",
      "Mr Ridgley Leo",
      "Ms Scarlet Barnwell",
      "Mr Bolton Tarin",
      "Ms Sevati Zepeda",
      "Mr Edison Loy",
      "Ms Vivien Ledoux",
      "Mr Delling Herndon",
      "Ms Dysis Fish",
      "Ms Sherry Fodor",
      "Ms Delanna Bowser",
      "Mr Senichi Iorio",
      "Ms Angela Denny",
      "Mr Albin Kerner",
      "Ms Janna Ying",
      "Mr Jivin Justus",
      "Mr Clement Fleisher",
    ];

    String randomName = " (Random name)";
    switch (petType) {
      case PetType.dog:
        return dogNames[Random().nextInt(dogNames.length)] + randomName;
      case PetType.cat:
        return catNames[Random().nextInt(catNames.length)] + randomName;
      case PetType.none:
        return 'Something wrong here';
    }
  }
}
