// Mocks generated by Mockito 5.2.0 from annotations
// in pets_app/test/ui/pages/listPets/controller/list_pets_screen_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pets_app/data/api/api.dart' as _i3;
import 'package:pets_app/domain/entities/entities.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponse_0 extends _i1.Fake implements _i2.Response {}

/// A class which mocks [ApiManagerClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManagerClient extends _i1.Mock implements _i3.ApiManagerClient {
  @override
  _i4.Future<_i2.Response> get(
          {String? endPoint,
          _i5.PetType? petType,
          Map<String, String>? headers,
          _i3.HttpClient? httpClient}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [], {
                #endPoint: endPoint,
                #petType: petType,
                #headers: headers,
                #httpClient: httpClient
              }),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i4.Future<_i2.Response>);
}
