// Mocks generated by Mockito 5.2.0 from annotations
// in pets_app/test/data/api/req_api_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:pets_app/data/api/req_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ReqAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockReqAPI extends _i1.Mock implements _i2.ReqAPI {
  MockReqAPI() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ReqAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockReqAPIRelaxed extends _i1.Mock implements _i2.ReqAPI {
  MockReqAPIRelaxed() {
    _i1.throwOnMissingStub(this);
  }
}
